name: Print Secret Value

on:

  push:

    branches:

      - main

      - DEVELOP
  workflow_dispatch:
jobs:

  print_value:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Print Secret Value

        run: echo ${{ secrets.SECRET_NAME }}
